# Generated by Django 2.1.1 on 2018-09-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('OLID', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightstand_dashboard.Book')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1023)),
                ('datetime', models.DateField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightstand_dashboard.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightstand_dashboard.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightstand_dashboard.Chapter')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightstand_dashboard.Reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='chapters',
            field=models.ManyToManyField(through='nightstand_dashboard.ReaderChapter', to='nightstand_dashboard.Chapter'),
        ),
        migrations.AddField(
            model_name='reader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='readers',
            field=models.ManyToManyField(related_name='groups', to='nightstand_dashboard.Reader'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to='nightstand_dashboard.Reader'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightstand_dashboard.Reader'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='readers',
            field=models.ManyToManyField(through='nightstand_dashboard.ReaderChapter', to='nightstand_dashboard.Reader'),
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='books', to='nightstand_dashboard.Reader'),
        ),
    ]
