# Generated by Django 2.1.1 on 2018-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightstand_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='reader',
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to='nightstand_dashboard.Reader'),
        ),
        migrations.AlterField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='books', to='nightstand_dashboard.Reader'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
